version: "3"

services:
  django:
    build:
      dockerfile: ./dockerfiles/prod/django.dockerfile
      context: .
    image: fitia-prod-django
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --pythonpath /home/app/django/src
    expose:
      - 8000
    depends_on:
      - postgres
    volumes:
      - static_data:/home/app/django/static
    env_file:
      - ./.env
    restart: unless-stopped
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
  nginx:
    build:
      dockerfile: ./dockerfiles/prod/nginx.dockerfile
      context: .
    image: fitia-prod-nginx
    volumes:
      - static_data:/home/app/django/static
    ports:
      - 80:80
    depends_on:
      - django
    restart: unless-stopped

volumes:
  postgres_data: {}
  static_data: {}
