# Generated by Django 4.1 on 2022-08-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_food_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="emoji",
            field=models.TextField(default="😋", verbose_name="emoji"),
        ),
    ]
