# Generated by Django 4.1 on 2022-08-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_food_emoji"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="emoji",
        ),
    ]
